### ISSUE TITLE
[BUG] Control panel doesnt appear and crashes panel

### ISSUE THREAD

**Issue by BoredDevNL** [EliverLara/kde_controlcentre#4]
**Describe the bug**
doesnt appear and crashes panel after logging out and logging back in

**To Reproduce**
1. install from kde-store
2. extract the .gz 
3. import the folder into the plasmoids folder
4. add widget to panel (doesnt show anything after adding it)
5. log in and log back out

**Expected behavior**
become visible, usable and not crash my panel.

**Desktop (please complete the following information):**
 - KDE Plasma Version: 5.27.11
 - Distribution: Linux mint XFCE 22
 - Qt Version: 5.13.13
 - KDE Frameworks Version: 5.1150

**Have you installed the following dependencies? Yes.**
 - `kdeplasma-addons`: 
 - `plasma-nm`: 
 - KDE Connect

**Comment by EliverLara** [comment]
I see now, it only works(for now) on plasma >= v6
